export const constants = {
    SELECT_SITE: 'SELECT_SITE',
    LOAD_SITE: 'LOAD_SITE',
    ADD_SITE: 'ADD_SITE',
    DELETE_SITE: 'DELETE_SITE',
    EDIT_SITE: 'EDIT_SITE',
    IN_PROGRESS: 'IN_PROGRESS',
    SITE_IN_PROGRESS: 'SITE_IN_PROGRESS',
    LOGIN_IN_PROGRESS: 'LOGIN_IN_PROGRESS',
    ALARM_IN_PROGRESS: 'ALARM_IN_PROGRESS',
}